      SUBROUTINE BAREXC(WT,C,AM,EROT,N,NM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INCLUDE 'SIZES'
C
C         BARRIER EXCITATION
C         SELECT MOMENTA FOR THE REACTION COORDINATE
C
      COMMON/PRLIST/T,V,H,TIME,NTZ,NT,ISEED0(8),NC,NX
      COMMON/WASTE/QQ(NDA3),PP(NDA3),WX,WY,WZ,L(NDA),NAM
      COMMON/QPDOT/Q(NDA3),PDOT(NDA3)
      COMMON/PQDOT/P(NDA3),QDOT(NDA3),W(NDA)
      COMMON/CONSTN/C1,C2,C3,C4,C5,C6,C7,PI,HALFPI,TWOPI
      COMMON/SADDLE/EBAR,TBAR,EZERO,NBAR 
      DIMENSION C(NDA3yf,NDA3yf),QCM(3),VCM(3)
    5 FORMAT(/4X,'REACTION COORDINATE ENERGY =',1PE18.9,' KCAL/MOL'/)
   15 FORMAT(15X,'INTERNAL ENERGY =',1PE18.9,' KCAL/MOL'/)
C
C         CALCULATE VELOCITY FOR REACTION COORDINATE
C         THE REACTION COORDINATE IS HELD FIXED 
C
C                 FIXED ENERGY FOR REACTION COORDINATE
C
      RAND=RAND0(ISEED)
      IF(NBAR.EQ.1) THEN
         SDUM=C1*EBAR
         PBAR=SQRT(2*SDUM)
C
C                 FIXED TEMPERATURE FOR REACTION COORDINATE
C
      ELSEIF(NBAR.EQ.2) THEN
         DUM=LOG(1.0D0-RAND)
         PBAR=SQRT(-2.0D0*C5*TBAR*DUM)
      ENDIF
C
      IF (RAND.GE.0.5D0) PBAR=-PBAR
      WRITE(6,5)0.5D0*PBAR*PBAR/C1
C
C         TRANSFORM FROM NORMAL MODE TO CARTESIAN VELOCITY
C
      DO I=1,N
         DO K=1,3
            JJ=3*I+1-K
            J=3*L(I)+1-K
            P(J)=P(J)+C(JJ,NM)*PBAR*W(L(I))
         ENDDO
      ENDDO
C
C         CALCULATE CENTER OF MASS COORDINATES QQ AND MOMENTA PP
C
      CALL CENMAS(WT,QCM,VCM,N)
C
C         MOVE PP ARRAY TO P ARRAY AND QQ ARRAY TO Q ARRAY
C
      DO I=1,N
         J=3*L(I)+1
         DO K=1,3
            Q(J-K)=QQ(J-K)
            P(J-K)=PP(J-K)
         ENDDO
      ENDDO
      CALL DVDQ
      CALL ENERGY
C
      CALL ROTN(AM,EROT,N)
C
      EINT=H-EZERO
      WRITE(6,15)EINT
C
      RETURN
      END
