      SUBROUTINE CPUSEC(TUSER,TTOTAL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z) 
C     
C         ROUTINE FOR TIMING (USER AND USER+SYSTEM TIME IN SECONDS).
C     
CUNIX VERSION FOR UNIX MACHINES WHICH PROVIDE A LIBRARY FUNCTION ETIME.
      REAL ETIME,TARRAY,TOTAL
      DIMENSION TARRAY(2)
      TTOTAL = ETIME(TARRAY)  !user + system execution time
      TUSER  = TARRAY(1)      !user time
CIBM  VERSION FOR IBM RS/6000 WHICH PROVIDES A LIBRARY FUNCTION MCLOCK.
C     INTEGER I
C     I      = MCLOCK()
C     TUSER  = I/100.0D0
CRAY  VERSION FOR CRAY WHICH PROVIDES A LIBRARY ROUTINE SECOND.
C     CALL SECOND(TUSER)
CNEC  VERSION FOR NEC WHICH PROVIDES A LIBRARY ROUTINE CLOCK.
C     CALL CLOCK(TUSER)
CSNI  VERSION FOR SNI-FUJITSU WHICH PROVIDES A LIBRARY ROUTINE CLOCK.
C     CALL CLOCK(TUSER,0,2)
CONV  VERSION FOR CONVEX WHICH PROVIDES A VECLIB FUNCTION CPUTIME.
C     REAL CPUTIME
C     TUSER  = CPUTIME(0.0)
      RETURN
      END
