      FUNCTION GAMA(IA,IDUM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         FUNCTION GAMA RETURNS A DEVIATE DISTRIBUTED AS A GAMMA 
C         DISTRIBUTION OF INTEGER ORDER IA
C
      DUM=1.0D0
      DO J=1,IA
         DUM=DUM*RAND0(IDUM)
      ENDDO
      GAMA=-LOG(DUM)
      RETURN
      END
