      SUBROUTINE GFINAL
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INCLUDE 'SIZES'
C
C         WRITE TRAJECTORY FINAL ANALYSIS RESULTS IN OUTPUT FILE
C
      COMMON/FINALB/EROTA,EROTB,EA(3),EB(3),AMA(4),AMB(4),AN,AJ,BN,BJ,
     *OAM(4),EREL,ERELSQ,BF,SDA,SDB,DELH(NDP),ANG(NDG),NFINAL
      COMMON/TESTB/RMAX(NDP),RBAR(NDP),NTEST,NPATHS,NABJ(NDP),NABK(NDP),
     *NABL(NDP),NABM(NDP),NPATH,NAST
      COMMON/SELTB/QZ(NDA3),NSELT,NSFLAG,NACTA,NACTB,NLINA,NLINB,NSURF
      COMMON/VECTB/VI(4),OAMI(4),AMAI(4),AMBI(4),ETAI,ERAI,ETBI,ERBI
      COMMON/FRAGB/WTA(NDP),WTB(NDP),LA(NDP,NDA),LB(NDP,NDA),
     *QZA(NDP,NDA3),QZB(NDP,NDA3),NATOMA(NDP),NATOMB(NDP)
      COMMON/PRLIST/T,V,H,TIME,NTZ,NT,ISEED0(8),NC,NX
      COMMON/FORCES/NATOMS,I3N,NST,NM,NB,NA,NLJ,NTAU,NEXP,NGHOST,NTET,
     *NVRR,NVRT,NVTT,NANG,NAXT,NSN2,NRYD,NHFD,NLEPSA,NLEPSB,NDMBE,
     *NRAX,NONB,NMO,NCRCO6
      COMMON/VMAXB/QVMAX(NDA3),PVMAX(NDA3),VMAX,NCVMAX
c      COMMON/HTURNL/NC1FLAG,NC1,NC2,NC3,HTMIN
C
    1 FORMAT(/)
    2 FORMAT(2X,26HREACTION OCCURRED FOR PATH,I3,5X,'ENERGIES IN KCAL ',
     *'AND ANGULAR MOMENTUM IN H-BAR'/)
    3 FORMAT(2X,'RESULTS FOR FRAGMENT A')
    4 FORMAT(4X,'TRAJ:',I5,2X,'TOTAL_ENERGY=',1PE14.7,3X,'VIB.ENERGY=',
     *E14.7,3X,'ROT.ENERGY=',E12.5,' +OR- ',E12.5,/,
     *4X,'TRAJ:',I5,2X,'ANG.MOMENTUM=',E12.5)
    5 FORMAT(/2X,'RESULTS FOR FRAGMENT B')
    6 FORMAT(/2X,'RELATIVE A+B PROPERTIES')
    7 FORMAT(4X,'TRAJ:',I5,2X,'REL.TRANS.ENERGY=',1PE12.5,3X,
     *'REL.TRANS.ENERGY+CEN.POTENTIAL=',E12.5/
     *4X,'TRAJ:',I5,2X,'ORB.ANG.MOMENTUM=',E12.5,
     *3X,'FINAL_B=',E12.5/)
    8 FORMAT(2X,'SCATTERING ANGLES IN DEGREES')
    9 FORMAT(4X,'TRAJ:',I5,'  LF,JAF: ',F7.2)
   10 FORMAT(4X,'TRAJ:',I5,'  LF,JBF: ',F7.2)
   11 FORMAT(4X,'TRAJ:',I5,'  JAF,JBF:',F7.2)
   12 FORMAT(4X,'TRAJ:',I5,'  VI,VF:  ',F7.2,5X,'LI,LF:  ',F7.2)
   13 FORMAT(4X,'TRAJ:',I5,'  LI,JAF: ',F7.2)
   14 FORMAT(4X,'TRAJ:',I5,'  LI,JBF: ',F7.2)
   15 FORMAT(4X,'TRAJ:',I5,'  JAI,LI: ',F7.2,5X,'JAI,LF: ',F7.2)
   16 FORMAT(4X,'TRAJ:',I5,'  JAI,JAF:',F7.2)
   17 FORMAT(4X,'TRAJ:',I5,'  JAI,JBF:',F7.2)
   18 FORMAT(4X,'TRAJ:',I5,'  JAI,JBI:',F7.2)
   19 FORMAT(4X,'TRAJ:',I5,'  JBI,LI: ',F7.2,5X,'JBI,LF: ',F7.2)
   20 FORMAT(4X,'TRAJ:',I5,'  JBI,JAF:',F7.2)
   21 FORMAT(4X,'TRAJ:',I5,'  JBI,JBF:',F7.2)
   22 FORMAT(4X,'TRAJ:',I5,'  PRODUCT IS A DIATOM:  N=',F6.2,3X,
     *'J=',F6.2)
   23 FORMAT(4X,'TRAJ:',I5,'  INCIDENT_ANG.(THETAf):',F7.2,
     *5X,'AZYMUTHAL_ANG.:',F7.2)
   30 FORMAT(/4X,'TRAJ:',I5,'  LIFETIME:',F12.3,' fs'/)
   36 FORMAT('TRAJ',I5,I10,E13.4)
   37 FORMAT(1X,3F10.3,3E15.5)
   38 FORMAT('TRAJ',I5,8F10.3)
c   40 FORMAT(/'  HEIGHT PROPERTIES FOR THE INCIDENT ATOM'/
c     *4X,'TRAJ:',I5,'  NC1,NC2,NC3,HTMIN:',3I7,F7.2/)
      WRITE(6,1)
      WRITE(6,*)'  ==== SUMMARY OF TRAJECTORY ===='
      TLIFE=TIME*NC*10.0
      WRITE(6,30)NTZ,TLIFE
      WRITE(6,2)NPATH
      WRITE(6,3)
      K=NATOMA(NPATH)
      IF (K.NE.1) THEN
         EVIB=EA(3)-EROTA
         WRITE(6,4)NTZ,EA(3),EVIB,EROTA,SDA,NTZ,AMA(4)
         IF (K.EQ.2) WRITE(6,22)NTZ,AN,AJ
      ENDIF
      K=NATOMB(NPATH)
      IF (K.NE.1) THEN
         WRITE(6,5)
         EVIB=EB(3)-EROTB
         WRITE(6,4)NTZ,EB(3),EVIB,EROTB,SDB,NTZ,AMB(4)
         IF (K.EQ.2) WRITE(6,22)NTZ,BN,BJ
      ENDIF
      WRITE(6,6)
      WRITE(6,7)NTZ,EREL,ERELSQ,NTZ,OAM(4),BF
      WRITE(6,8)
      IF (NATOMA(NPATH).GT.1) WRITE(6,9)NTZ,ANG(1)
      IF (NATOMB(NPATH).NE.1) THEN
         WRITE(6,10)NTZ,ANG(2)
         IF (NATOMA(NPATH).NE.1) WRITE(6,11)NTZ,ANG(3)
      ENDIF
      IF (NATOMB(1).NE.0) THEN
         WRITE(6,12)NTZ,ANG(4),ANG(5)
         IF (NATOMA(NPATH).GT.1) WRITE(6,13)NTZ,ANG(6)
         IF (NATOMB(NPATH).GT.1) WRITE(6,14)NTZ,ANG(7)
         IF (AMAI(4).GE.1.00D-05) THEN
            WRITE(6,15)NTZ,ANG(8),ANG(9)
            IF (NATOMA(NPATH).GT.1) WRITE(6,16)NTZ,ANG(10)
            IF (NATOMB(NPATH).GT.1) WRITE(6,17)NTZ,ANG(11)
            IF (AMBI(4).LT.1.00D-05) GOTO 100
            WRITE(6,18)NTZ,ANG(12)
         ENDIF
         IF (AMBI(4).LT.1.00D-05) GOTO 100
         WRITE(6,19)NTZ,ANG(13),ANG(14)
         IF (NATOMA(NPATH).GT.1) WRITE(6,20)NTZ,ANG(15)
         IF (NATOMB(NPATH).GT.1) WRITE(6,21)NTZ,ANG(16)
      ENDIF
  100 WRITE(6,*)
      IF (NSURF .NE. 0) THEN
         WRITE(6,23)NTZ,ANG(17),ANG(18)
c         WRITE(6,40)NTZ,NC1,NC2,NC3,HTMIN
      ENDIF
      WRITE(9,38)NTZ,ERELSQ,OAMI(4),OAM(4),ANG(4)
      WRITE(10,38)NTZ,ETAI,ERAI,EA(3),EROTA,SDA,AMAI(4),AMA(4)
      WRITE(11,38)NTZ,ETBI,ERBI,EB(3),EROTB,SDB,AMBI(4),AMB(4)
      WRITE(17,36)NTZ,NCVMAX,VMAX
C      J=1
C      DO I=1,NATOMS
C      K=J+2
C      WRITE(17,37)(QVMAX(II),II=J,K),(PVMAX(II),II=J,K)
C      J=K+1
C      ENDDO
c     
      CALL FLUSH(6)
      CALL FLUSH(9)
      CALL FLUSH(10)
      CALL FLUSH(11)
C
      RETURN
      END
