      SUBROUTINE GRCONV(QM,GZ)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INCLUDE 'SIZES'
C
C          CALCULATE MASS-WEIGHTED AND NORMALIZED GRADIENT
C          FOR REACTION PATH FOLLOWING
C
      COMMON/WASTE/QQ(NDA3),PP(NDA3),WX,WY,WZ,LL(NDA),NAM
      COMMON/FORCES/NATOMS,I3N,NST,NM,NB,NA,NLJ,NTAU,NEXP,NGHOST,NTET,
     *NVRR,NVRT,NVTT,NANG,NAXT,NSN2,NRYD,NHFD,NLEPSA,NLEPSB,NDMBE,
     *NRAX,NONB,NMO,NCRCO6
      COMMON/QPDOT/Q(NDA3),PDOT(NDA3)
      COMMON/PQDOT/P(NDA3),QDOT(NDA3),W(NDA)
      COMMON/FR2/DG(NDA3,2),DIM(NDA3)
      DIMENSION QM(NDA3),GZ(NDA3)
      DO I=1,I3N
         Q(I)=QM(I)*DIM(I)
      ENDDO
      CALL DVDQ
      DUM=0.0D0
      DO I=1,I3N
         GZ(I)=-PDOT(I)*DIM(I)
         DUM=DUM+GZ(I)*GZ(I)
      ENDDO
      DUM=SQRT(DUM)
      DO I=1,I3N
         GZ(I)=GZ(I)/DUM
      ENDDO
      RETURN
      END
