      SUBROUTINE POTENZ(II)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INCLUDE 'SIZES'
      
C         
C         SETS THE COORDINATES FOR REACTANTS OR PRODUCTS TO THEIR
C         EQUILIBRIUM VALUES, DISPLACES A AND B, AND CALCULATES THE
C         POTENTIAL ENERGY
C
      COMMON/PRLIST/T,V,H,TIME,NTZ,NT,ISEED0(8),NC,NX
      COMMON/QPDOT/Q(NDA3),PDOT(NDA3)
      COMMON/PQDOT/P(NDA3),QDOT(NDA3),W(NDA)
      COMMON/FRAGB/WTA(NDP),WTB(NDP),LA(NDP,NDA),LB(NDP,NDA),
     *QZA(NDP,NDA3),QZB(NDP,NDA3),NATOMA(NDP),NATOMB(NDP)
C
C         INITIALIZE Q AND P ARRAYS
C
      
      J=3*NATOMA(II)
      DO I=1,J
         Q(I)=QZA(II,I)
         P(I)=0.0D0
      ENDDO
      K=3*NATOMB(II)       
      DO I=1,K
         Q(J+I)=QZB(II,I)
         P(J+I)=0.0D0
      ENDDO
      call DVDQ
      call ENERGY

C
C         SEPARATE A AND B BY 1000 ANGSTROMS
C

      IF(NATOMB(II).GT.0)THEN 
        DO I=1,NATOMB(II)
          J3=3*LB(II,I)
          Q(J3)=Q(J3)+1000.0D0
        ENDDO
      ENDIF

C         CALCULATE THE A + B POTENTIAL ENERGY, WITH A + B SEPARATED
C         BY 1000 ANGSTROMS.
C      
      VZERO = 0.0D0 
      CALL DVDQ
      CALL ENERGY


C         REMOVE THE 1000 ANGSTROM SEPARATION BETWEEN A AND B
C
      IF(NATOMB(II).GT.0)THEN 
        DO I=1,NATOMB(II)
          J3=3*LB(II,I)
          Q(J3)=Q(J3)-1000.0D0
          ENDDO
      ENDIF
C
      RETURN
      END
