      FUNCTION RAND0(IDUM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         FUNCTION RAND0(IDUM)
C         GETS THE NEXT RANDOM NUMBER FROM A SEQUENCE OF RANDOM NUMBERS
C         BY SHUFFLING THE SEQUENCE
C
C         REFERENCE: D.E. KNUTH, "THE ART OF COMPUTER PROGRAMMING",
C         VOL. 2 OF "SEMINUMERICAL ALGORITHMS" (ADDISON-WESLEY, 1981),
C         2ND EDITION. (PG. 32)
C
C         WRITTEN BY DAVID SCHWENKE (NASA AMES)
C         AMENDED BY KIERAN F. LIM (STANFORD UNIVERSITY)
C
C         IDUM IS A DUMMY NUMBER
C
      COMMON/RANCOM/RANLST(100),ISEED3(8),IBFCTR
      J=INT(99E0*RANLST(100))+1
      RAND0 = RANLST(100)
      RANLST(100)=RANLST(J)
      RANLST(J)=RAND1(ISEED3)
      RETURN
      END
