      SUBROUTINE THRMAN(WW,ANQ,T,NM)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INCLUDE 'SIZES'
C
C         CALCULATE VIBRATIONAL QUANTUM NUMBERS FROM A THERMAL
C         (BOLTZMAN) DISTRIBUTION
C
      COMMON/CONSTN/C1,C2,C3,C4,C5,C6,C7,PI,HALFPI,TWOPI
      DIMENSION WW(NDA3),ANQ(NDA3)
C
      DUM1=C7/C5/T
      DO I=1,NM
         DUM=DUM1*WW(I)
         N=GAMA(1,ISEED)/DUM 
         ANQ(I)=DBLE(N)
      ENDDO
      RETURN
      END
